dad=input("ENTER YOUR BRITHDAY MONTH AND DATE DAD:")
mom=input("ENTER YOUR BIRTHDAY MONTH AND DATE MOM:")
brother=input("ENTER YOUR BIRTHDAY MONTH AND DATE BRO:")
sister=input("ENTER YOUR BIRTHDAY MONTH AND DATE SIS:")
print("___________________________________________________________")
print("FAMILY BIRTHDAYS:")
print("FATHERS BIRTHDAY IS ON",dad)
print("MOTHERS BIRTHDAY IS ON",mom)
print("BROTHERS BIRTHDAY IS ON",brother)
print("SISTERS BIRTHDAY IS ON",sister)
print("___________________________________________________________")